# 配置端口
server:
  port: 8080
  servlet:
    session:
      timeout: 21600

# 配置mysql数据库
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.149.252:3306/blog?serverTimezone=Asia/Shanghai&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # redis配置
  redis:
    host: 124.221.149.252
    port: 6379
    password: 123456
  # mq配置
  rabbitmq:
    host: 124.221.149.252
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3 #最大重试次数
          initial-interval: 3000 #重试间隔时间（单位毫秒）
  # es配置 若搜索模式为mysql可删除
  elasticsearch:
    rest:
      uris: 124.221.149.252:9200
  # 邮箱配置（邮件回复通知）
  mail:
    host: smtp.qq.com
    username: yunlongyu666@qq.com
    password: jxxreftypqdjcaef
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
      smtp:
      auth: true
      socketFactory:
      class: javax.net.ssl.SSLSocketFactory
  # 上传图片大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size:  100MB

# 配置MybatisPlus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 搜索模式 可选 elasticsearch或mysql
search:
  mode: elasticsearch


# 上传模式 可选 oss或local  （http://和最后的/一定不能去！！！）
upload:
  mode: oss
  local:
    # 文件上传子域名,无域名则为 ip:83
    url: https://www.static.yuyunlong.cn/
    # nginx映射本地文件路径
    path: /usr/local/upload/
  oss:
    url: https://yylblogbucket.oss-cn-shanghai.aliyuncs.com/
    endpoint: http://oss-cn-shanghai.aliyuncs.com/
    accessKeyId: LTAI5tS5Ldg2ecsVLKpGfBpB
    accessKeySecret: qUybirBeYIQaxQtvlkCgNr1egq2FYW
    bucketName: yylblogbucket

# 网站前台域名（邮件通知，邮件显示网站地址）
website:
  url: https://www.yuyunlong.cn

#第三方配置信息
qq:
  app-id: 102000210
  check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
  user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}

weibo:
  app-id: 微博APPID
  app-secret: 微博APPSECRET
  grant-type: authorization_code
  redirect-url: https://www.yuyunlong.cn/oauth/login/weibo
  access-token-url: https://api.weibo.com/oauth2/access_token
  user-info-url: https://api.weibo.com/2/users/show.json?uid={uid}&access_token={access_token}
